FROM python:latest

RUN apt-get update && apt-get install -y --no-install-recommends \
    postgresql-client dos2unix && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /script

COPY database/startup .

COPY server/gin/server_tests.sh .

RUN chmod +x /script/docker_db.sh

RUN chmod +x /script/server_tests.sh

RUN dos2unix docker_db.sh

RUN dos2unix server_tests.sh

RUN pip install -r requirements.txt

CMD ["sh", "-c", "./docker_db.sh && ./server_tests.sh"]
